#-----------------------------------------------------------------------------------------------------------------------
#
# COPY this file. DO NOT commit to svn
#
# Yahoo PlaceFinder -- https://developer.apps.yahoo.com/projects -- jason_younker@yahoo.com
#
#-----------------------------------------------------------------------------------------------------------------------
test:
    domain: localhost:3000
    encryption:
      password: 'f438229716cab43569496f3a3630b3727524b81b'
    email:
        mailbox_username: younker_test
        mailbox_password: test
        generic_from: ehouseoffers@28dev.com
        contact_form_recipient: ehouseoffers@28dev.com
    placefinder:
      api_key: 'dj0yJmk9RklQeDNnZVhReXl6JmQ9WVdrOVF6bHplV1l6TTJVbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD02Yw--'
      shared_secret: '4d7d5ff0f2fd6285c0c94d8b59df02e4b4736723'
      app_id: 'C9syf33e'
      base: 'http://where.yahooapis.com/geocode'
    twitter:
      base: "http://twitter.com/share"
      username: ynkr
    linkedin:
      base: 'http://www.linkedin.com/shareArticle'
      source: '28dev.com'
    facebook:
      app_name: ynkr
      app_url: 'http://www.ynkr.org/'
      app_id: '138541152866086'
      app_secret: '07b63899d7c2257b53a560f8d76866e9'
    salesforce:
      base: 'https://test.salesforce.com/services/Soap/c/20.0'
      username: 'ehouseoffers@28dev.com.eho'
      password: 'eH0use0ffers'
      token: 'TWy65qVwBXaFdtCzWgYUaG2D'
      default_account_id: '001C000000nnPUcIAM'

development:
    domain: localhost:3000
    encryption:
      password: '35bc1e79038fa88673fa64b094b92bb79fa571b1'
    email:
        mailbox_username: younker_test
        mailbox_password: test
        generic_from: ehouseoffers@28dev.com
        contact_form_recipient: ehouseoffers@28dev.com
    placefinder:
      api_key: 'dj0yJmk9RklQeDNnZVhReXl6JmQ9WVdrOVF6bHplV1l6TTJVbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD02Yw--'
      shared_secret: '4d7d5ff0f2fd6285c0c94d8b59df02e4b4736723'
      app_id: 'C9syf33e'
      base: 'http://where.yahooapis.com/geocode'
    twitter:
      base: "http://twitter.com/share"
      username: ynkr
    linkedin:
      base: 'http://www.linkedin.com/shareArticle'
    facebook:
      app_name: ynkr
      app_url: 'http://www.ynkr.org/'
      app_id: '138541152866086'
      app_secret: '07b63899d7c2257b53a560f8d76866e9'
    salesforce:
      base: 'https://www.salesforce.com/services/Soap/u/10.0'
      username: 'ehouseoffers@28dev.com'
      password: 'eH0use0ffers'
      token: 'HEazAX4dUK1t8LRXFOViTysH'
      default_account_id: '001C000000nnPUcIAM'

staging:
    domain: localhost:3000
    encryption:
      password: '190c3c31098e943d0faeb91d2c1c00e0f70bd086'
    email:
        mailbox_username: younker_test
        mailbox_password: test
        generic_from: ehouseoffers@28dev.com
        contact_form_recipient: ehouseoffers@28dev.com
    placefinder:
      api_key: 'dj0yJmk9RklQeDNnZVhReXl6JmQ9WVdrOVF6bHplV1l6TTJVbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD02Yw--'
      shared_secret: '4d7d5ff0f2fd6285c0c94d8b59df02e4b4736723'
      app_id: 'C9syf33e'
      base: 'http://where.yahooapis.com/geocode'
    twitter:
      base: "http://twitter.com/share"
      username: ehouseoffers
    linkedin:
      base: 'http://www.linkedin.com/shareArticle'
    facebook:
      app_name: ynkr
      app_url: 'http://www.ynkr.org/'
      app_id: '138541152866086'
      app_secret: '07b63899d7c2257b53a560f8d76866e9'
    salesforce:
      base: 'https://www.salesforce.com/services/Soap/u/10.0'
      username: 'ehouseoffers@28dev.com'
      password: 'eH0use0ffers'
      token: 'HEazAX4dUK1t8LRXFOViTysH'
      default_account_id: '001C000000nnPUcIAM'
